#exclude the following files from coverage reports
exclude_files:
    - src/problems/RockSample/rockSampleInt.jl
    - src/upperBound/DESPOTDefaultUpperBound.jl
    - src/problems/RockSample/runRockSampleInt.jl
    - src/lowerBound/DESPOTDefaultLowerBound.jl
