language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false
before_script:
  - export PATH=$HOME/.local/bin:$PATH
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.clone("https://github.com/JuliaPOMDP/POMDPs.jl"); Pkg.clone("https://github.com/JuliaPOMDP/POMDPToolbox.jl"); Pkg.build("DESPOT"); Pkg.test("DESPOT"; coverage=true)'
